name: chaloapp
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  intl: ^0.16.1
  path_provider: ^1.6.11
  simple_animations: ^1.3.3
  font_awesome_flutter: ^8.2.0
  gender_selection: "^0.0.8"
  datetime_picker_formfield: ^1.0.0
  shared_preferences: ^0.5.7+2
  toast: ^0.1.5
  steel_crypt: ^1.7.1+1
  flutter_map:
  firebase_auth: 
  firebase_storage:
  cloud_firestore: 
  firebase_messaging:
  firebase_dynamic_links: ^0.5.0+11
  google_sign_in: ^4.5.0
  flutter_facebook_login: ^2.0.1
  flutter_spinkit: "^4.1.2"
  image_picker: ^0.6.6+1
  image_cropper: ^1.2.3
  like_button: ^0.2.0
  mapbox_search_flutter:
  latlong: ^0.6.1
  location: ^2.3.5
  geolocator: ^5.3.1
  geocoder: ^0.2.1
  flutter_slidable: "^0.5.4"
  onesignal_flutter: ^2.5.0
  share: ^0.6.4+3
  http: ^0.12.1
  flappy_search_bar: ^1.7.2
  smooth_star_rating: ^1.1.1
  animations: ^1.1.1



dev_dependencies:
  flutter_test:
    sdk: flutter




# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec



flutter:
  uses-material-design: true
  assets:
    - images/
    - images/activities/
    - images/post/

  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
    - family: Karla
      fonts:
        - asset: fonts/Karla-Regular.ttf
    - family: PlayfairDisplay
      fonts:
        - asset: fonts/PlayfairDisplay-Regular.ttf
